from .Home import home
from .SignUp import signUp
from .SignIn import signIn
from .Register import register
from .galleryPage import galleryPage
from .event import event
from .about import about
from .eventinfo import eventinfo
from .admin import admin_page