from .navbar import navbar
from .footer import footer
from .form import form_example
from .form1 import signup_form
from .registerform import register_form
from .gallery import gallery_cards
from .eventform import event_form
from .FeaturedVideo import featuredVideo
from .upcomingEvents import upcomingEvents
from .about import about_page
from .eventdetails import event_details